### ISSUE TITLE
missed unit_of_measurement

### ISSUE THREAD

**Issue by krom** [TheTinkerDad/sensible#8]
Your excample sensor provide text sensor with human friendly unit of measurement

```yaml
- name: Sensible Root Disk Free
  kind: script
  sensorid: root_free
  script: root_free.sh
  icon: mdi:harddisk
```

and script

```shell
#!/bin/sh
df  /  -h | tail -n 1 | awk '/ / {print $4}'
```

But it's not good solution because it's not useful for authomations and graphs

I've replaces config to

```yaml
- name: Sensible Root Disk Free
  kind: script
  sensorid: root_free
  script: root_free.sh
  unit_of_measurement: GB
  icon: mdi:harddisk
```

and script to

```shell
#!/bin/sh
df / | tail -n 1 | awk '/ / {print $4 / 1048576}'
```

But `unit_of_measurement` does not exist in config.

Could you please provide `unit_of_measurement` and change your configs

This issue is related to #4
